from typing import Protocol


class ISenderMonitor(Protocol):
    def get_avg_load_pct(self) -> float: ...
    def get_high_load_time_pct(self) -> float: ...
    def get_sent_bytes_per_sec(self) -> float: ...
    def get_sent_messages_per_sec(self) -> float: ...
    def get_dropped_logs_total(self) -> int: ...
    def get_dropped_custom_total(self) -> int: ...